---
resource_types:
- name: cf
  type: docker-image
  source:
    repository: concourse/cf-resource

resources:
- name: hk-development
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: ((pws_bot.username))
    password: ((pws_bot.password))
    organization: haut-kultur-org
    space: development

- name: concourse-generics
  type: git
  source:
    uri: https://github.com/ships/concourse-generics
    branch: master

- name: this
  type: git
  source:
    uri: git@github.com:ships/cryptocurrency-origins
    branch: master
    private_key: ((github_ssh_ships.private_key))

jobs:
- name: audit
  plan:
  - in_parallel:
    - get: this
      trigger: true
    - get: concourse-generics
  - task: audit
    file: concourse-generics/audit/linux/node.yml
    input_mapping: {subject: this}
    on_failure:
      do:
      - task: fix
        file: this/ci/audit/fix.yml
        input_mapping: {subject: this}
      - task: commit
        file: concourse-generics/git/linux/make-commit.yml
        input_mapping: {src: dirty}
        output_mapping: {out: bumped-this}
        params:
          SUBJECT: security audit patch dependencies
          COMMITTER_NAME: early evening
          COMMITTER_EMAIL: eve@eatbigger.fish
      - task: audit-again
        file: concourse-ci/audit/linux/node.yml
        input_mapping: {subject: bumped-this}
      - put: this
        params:
          repository: bumped-this

- name: update-development
  plan:
  - get: this
    trigger: true
    passed: [audit]
  - task: build
    file: this/ci/build/task.yml
    input_mapping: {subject: this}
  - put: hk-development
    params:
      path: dirty
      manifest: this/manifest.yml


